### ISSUE TITLE
[Style] 메인페이지 나의 단어 화면 구현

### ISSUE THREAD

**Issue by seung1** [GDSC-CAU/FTIsland-FE#12]
## 📌 Issue 내용

- 메인페이지에서 나의 단어 화면 구현합니다.

<br/>

## 📝 TO DO

- [x] 단어카드 만들기
- [x] 레이아웃 구성
- [x] 클릭했을때 뒤돌아지는 애니메이션
- [x] 즐겨찾기 삭제하는 버튼 추가
- [x] tts 기능 추가
- [ ] [피드백] 이미지 최적화 적용

<br/>

## 💌 비고

- 뒤 돌아지는 애니메이션이 너무 저렴해져보일경우, 다른 애니메이션 강구

**Comment by minusmo** [comment]
최종적으로 이미지가 많이 필요한, 혹은 고해상도 이미지가 필요한 서비스가 될 경우 나중에 이미지 로드 최적화를 고려해보면 좋겠습니다~ 
- 이미지 파일 압축, 변환(e.g. WebP)
- 이미지 전송 방법 최적화(e.g. HTTP/2, HTTP/3)
- 지연 로딩(e.g. Lazy Loading)
등 여러 방법이 있습니다. 
나중에 꼭 필요한 경우가 생기고 여유가 된다면 적용을 고려해보면 됩니다.
화이팅입니다~ 🦾
